const express = require("express");
const mainRouter=require('./routes/index');
const userRouter=require('./routes/user');
const app=express();
const cors=require('cors');
app.use("/api/v1",mainRouter);
app.use("/api/v1/user",userRouter);
app.use(cors());
app.use(express.json());
app.listen(3000);